zookeeper:
  image: garland/zookeeper
  net: host
  ports:
    - "2181:2181"

mesos-master:
  image: mesoscloud/mesos-master
  net: host
  ports:
    - "5050:5050"
  environment:
    - MESOS_ZK=zk://127.0.0.1:2181/mesos
    - MESOS_LOG_DIR=/var/log/mesos
    - MESOS_QUORUM=1
    - MESOS_REGISTRY=in_memory
    - MESOS_WORK_DIR=/var/lib/mesos
    - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=10mins

mesos-slave:
  image: mesoscloud/mesos-slave
  ports:
    - "5051:5051"
  mem_limit: 4096m
  net: host
  restart: on-failure
  environment:
    - MESOS_MASTER=zk://127.0.0.1:2181/mesos
    - MESOS_LOG_DIR=/var/log/mesos
    - MESOS_LOGGING_LEVEL=INFO

marathon:
  image: mesoscloud/marathon
  net: host
  ports:
    - "8080:8080"
    - "2888:2888"
    - "3888:3888"
  environment:
    - MARATHON_MASTER=zk://127.0.0.1:2181/mesos
    - MARATHON_ZK=zk://127.0.0.1:2181/marathon
    - MARATHON_HOSTNAME=marathon

cassandra:
  image: cassandra:2.2
  net: host
  ports:
    - "9042:9042"

stack-deploy:
  build: .
  net: host
  restart: on-failure
  command: stack-deploy server --marathon http://localhost:8080 --cassandra=localhost:9042 --master localhost:5050 --debug
  ports:
    - "4200:4200"
